<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2ec50e5d-2aa3-45c5-b2ae-ecca9c4ca1e3</elementGuidId>
    <imagePath></imagePath>
    <name>button_back_to_products</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#back-to-products</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'back-to-products') and equals(@name,'back-to-products') and equals(@class,'btn btn_secondary back btn_large inventory_details_back_button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_secondary back btn_large inventory_details_back_button</value>
        <webElementGuid>97c9d578-2357-4c12-b45f-4d0a64666ba8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>back-to-products</value>
        <webElementGuid>f45d4fb7-adfa-49a5-bc05-3b00d692bb9b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>back-to-products</value>
        <webElementGuid>97c18eeb-ac90-49a9-9341-1560b76fd5f2</webElementGuid>
    </webElementProperties>
</WebElementEntity>